version: '3'
services:
  contract:
    container_name: contract
    build: ./contract-service
    ports:
      - "8081:8081"
    depends_on:
      - "db"

  cashkick:
    container_name: cashkick
    build: ./cashkick-service
    ports:
      - "8082:8082"
    depends_on:
      - "db"

  notification:
    container_name: notification
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - "db"

  user:
    container_name: user
    build: ./user-service
    ports:
      - "8084:8084"
    depends_on:
      - "db"

  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local