BEGIN TRANSACTION;

INSERT INTO CASHKICK_STATUS VALUES ('PENDG', 'Pending');
INSERT INTO CASHKICK_STATUS VALUES ('APPR', 'Approved');
INSERT INTO CASHKICK_STATUS VALUES ('REJTD', 'Rejected');

INSERT INTO PAYMENT_STATUS VALUES('UPC', 'Upcoming');

COMMIT TRANSACTION;