version: '3.1'

services:
  
  cashkick-service :
    image: malyadr/cashkick_22:1
    container_name: Service-Registry 
    restart: always
    ports:
     - 8082:8082

  contract-service : 
    image: malyadr/contract_22:1
    container_name: Skills-microservice 
    restart: always
    ports:
     - 8081:8081
  
  notification-service:
    image: malyadr/notification_22:1
    container_name: microservice-location
    restart: always
    ports:
     - 8083:8083

  reporting-service :
    image: malyadr/reporting_22:1
    container_name: routes-microservice 
    restart: always
    ports:
     - 8085:8085

  user-service :
    image: malyadr/user_22:1
    container_name: jobs-microservice
    restart: always
    ports:
     - 8084:8084