image: 
   name: amazon/aws-cli
   entrypoint: [""]   
services:
    - name: docker:20-dind
      command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

stages:
    - Build image and Push to Docker Hub
    - deploy
docker build and push:
    stage: Build image and Push to Docker Hub
    only:
        - deployment

    before_script:
        - amazon-linux-extras install docker
        - aws --version
        - docker --version
        - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    script:
        - cd seeder-react-ts
        - docker build . -t varunbootcamp1111:1
        - docker tag varunbootcamp1111:1 "$REGISTRY_USER"/varun_bc122:1
        - docker push "$REGISTRY_USER"/varun_bc122:1
    environment:
       name: staging
       url:
deploy:
  stage: deploy  
  image: kroniak/ssh-client
   
  before_script:
      - mkdir ~/.ssh
      - echo -e "$KEY_PAIR" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script: 
    - ssh ubuntu@3.135.233.218 "sudo docker stop frontend"
    - ssh ubuntu@3.135.233.218 "sudo docker rm frontend"
    - ssh ubuntu@3.135.233.218 "sudo docker rmi "$REGISTRY_USER"/varun_bc11111:1"
    - ssh ubuntu@3.135.233.218 "sudo docker pull "$REGISTRY_USER"/varun_bc122:1"  
    - ssh ubuntu@3.135.233.218 "sudo docker run -d --name frontend -p 3042:3042  "$REGISTRY_USER"/varun_bc122:1"
    - exit
 
   
  only:
    - deployment
  environment:
      name: production
      url: 

